import type { Metadata } from "next";
import "./globals.css";
// Generated by @zee-css/cli — see `npm run zee:build`.
// Imported after globals.css so utilities win the cascade.
import "./zee.css";
import { Sidebar, PrevNext } from "./_components/Nav";

export const metadata: Metadata = {
  title: "zee-css — live utility docs",
  description:
    "Every zee-css utility, demonstrated in a Next.js app that is itself styled entirely with zee-css.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="grid grid-cols-1 lg:grid-cols-5 xl:grid-cols-6 min-h-[100vh]">
          <div className="lg:col-span-1">
            <Sidebar />
          </div>
          <main className="lg:col-span-4 xl:col-span-5 pa-6 md:pa-10 lg:pa-12 overflow-x-hidden">
            <div className="mx-auto max-w-[68rem]">
              {children}
              <PrevNext />
              <footer className="mt-12 pt-8 border-t border-slate-200 dark:border-slate-800 text-caption text-slate-400 dark:text-slate-600">
                Built with{" "}
                <code className="font-mono text-slate-500 dark:text-slate-500">
                  @zee-css/core
                </code>{" "}
                and{" "}
                <code className="font-mono text-slate-500 dark:text-slate-500">
                  @zee-css/cli
                </code>{" "}
                — ISC © praballl
              </footer>
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}
