import Link from "next/link";
import { generateCSS } from "@zee-css/core";
import { Section, Demo, Code, Callout } from "./_components/ui";
import { ROUTES } from "./_components/routes";

const FEATURES = [
  ["415 rule patterns", "Spacing, layout, grid, typography, color, effects, transforms, interactivity."],
  ["242 colors", "22 Tailwind families x 11 shades, plus 7 CSS-variable theme tokens."],
  ["Tree-shaken", "The CLI scans your source and emits CSS only for classes you actually wrote."],
  ["Zero runtime deps", "@zee-css/core ships no dependencies. The whole engine is plain TypeScript."],
  ["Programmable", "generateCSS() is a public API. Add colors, move breakpoints, generate at build time."],
  ["O(1) cache", "Repeated class lookups are memoized, so incremental rebuilds stay fast."],
];

export default function Home() {
  // Runs on the server, against the installed package — this is real output.
  const sample = generateCSS(["pa-6", "md:pa-8", "hover:bg-indigo-600", "dark:text-white"]);

  return (
    <>
      <header className="mb-16">
        <p className="text-overline text-indigo-600 dark:text-indigo-400 mb-3">
          Utility CSS, written in TypeScript
        </p>
        <h1 className="text-h2 font-black tracking-tight mb-6 bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 bg-clip-text text-transparent">
          zee-css
        </h1>
        <p className="text-body1 leading-relaxed text-slate-600 dark:text-slate-400 max-w-[62ch] mb-8">
          A high-performance utility CSS framework with a fully programmable
          core. This entire site — every border, every gradient, every hover
          state — is styled with nothing but zee-css utilities generated by{" "}
          <code className="font-mono text-indigo-700 dark:text-indigo-300">@zee-css/cli</code>.
        </p>
        <div className="flex flex-wrap gap-3">
          <Link
            href="/spacing"
            className="px-5 py-3 rounded-lg bg-indigo-600 text-white text-body2 font-semibold shadow-lg hover:bg-indigo-700 transition-colors duration-200"
          >
            Browse the utilities
          </Link>
          <Link
            href="/api"
            className="px-5 py-3 rounded-lg border border-slate-300 dark:border-slate-700 text-body2 font-semibold text-slate-700 dark:text-slate-300 hover:bg-slate-100 transition-colors duration-200"
          >
            Programmatic API
          </Link>
        </div>
      </header>

      <Section
        id="install"
        title="Install"
        description="Both packages are published on npm. The core is the generation engine; the CLI scans your files and writes the stylesheet."
      >
        <Code>{`npm install @zee-css/core
npm install -D @zee-css/cli`}</Code>
      </Section>

      <Section
        id="wiring"
        title="Wiring it into Next.js"
        description="The CLI scans <dir>/src/**, which lines up with the src/app layout this project uses. It writes one stylesheet; you import it once in the root layout."
      >
        <Code>{`// package.json
"scripts": {
  "zee:build": "zee-css . -o src/app/zee.css",
  "zee:watch": "zee-css . -o src/app/zee.css --watch",
  "dev":       "npm run zee:build && next dev",
  "build":     "npm run zee:build && next build"
}`}</Code>
        <Code>{`// src/app/layout.tsx
import "./globals.css";   // reset + theme tokens
import "./zee.css";       // <- generated by @zee-css/cli`}</Code>
        <Callout tone="info" title="Why the CSS is committed">
          <code className="font-mono">zee.css</code> is regenerated by{" "}
          <code className="font-mono">npm run dev</code> and{" "}
          <code className="font-mono">npm run build</code> before Next.js starts,
          so it is always in sync with the classes in your source tree.
        </Callout>
      </Section>

      <Section
        id="live"
        title="Live output"
        description="The block below was produced by calling generateCSS() from a React Server Component while this page rendered. It is not a copied snippet."
      >
        <Code>{sample.trim()}</Code>
      </Section>

      <Section id="features" title="What you get">
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
          {FEATURES.map(([title, body]) => (
            <div
              key={title}
              className="pa-5 rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 hover:shadow-lg transition-shadow duration-200"
            >
              <p className="text-body2 font-semibold text-slate-900 dark:text-white mb-2">
                {title}
              </p>
              <p className="text-caption leading-relaxed text-slate-600 dark:text-slate-400">
                {body}
              </p>
            </div>
          ))}
        </div>
      </Section>

      <Section
        id="taste"
        title="A taste of the syntax"
        description="Utilities compose the way you would expect, and variants stack left to right."
      >
        <Demo code="pa-6 rounded-xl bg-gradient-to-br from-indigo-500 to-purple-600 text-white shadow-xl">
          <div className="pa-6 rounded-xl bg-gradient-to-br from-indigo-500 to-purple-600 text-white shadow-xl">
            <p className="text-body1 font-semibold">Gradient card</p>
            <p className="text-caption opacity-80">Four utilities, no CSS file.</p>
          </div>
        </Demo>

        <Demo code="hover:scale-105 hover:shadow-2xl transition duration-300">
          <div className="pa-6 rounded-xl bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 hover:scale-105 hover:shadow-2xl transition duration-300 cursor-pointer">
            <p className="text-body2 font-medium text-slate-800 dark:text-slate-200">
              Hover me
            </p>
          </div>
        </Demo>

        <Demo code="grid-cols-2 md:grid-cols-4 gap-3" note="resize the window">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
            {[1, 2, 3, 4].map((n) => (
              <div
                key={n}
                className="pa-4 rounded-lg bg-indigo-100 dark:bg-indigo-900 text-indigo-700 dark:text-indigo-300 text-center text-caption font-semibold"
              >
                {n}
              </div>
            ))}
          </div>
        </Demo>
      </Section>

      <Section
        id="map"
        title="Everything in this reference"
        description="Each page demonstrates a category with live examples and the CSS the library actually emits."
      >
        <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-3">
          {ROUTES.filter((r) => r.href !== "/").map((r) => (
            <Link
              key={r.href}
              href={r.href}
              className="pa-4 rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 hover:border-indigo-400 transition-colors duration-200"
            >
              <p className="text-body2 font-semibold text-slate-900 dark:text-white">
                {r.label}
              </p>
              <p className="text-caption text-slate-500 dark:text-slate-500">
                {r.blurb}
              </p>
            </Link>
          ))}
        </div>
      </Section>
    </>
  );
}
