/* AUTO-GENERATED by scripts/zee-audit.mjs — do not edit by hand.
 *
 * The @zee-css/cli v1.0.0 scanner reads className="..." attributes only, so
 * classes written inside a conditional expression never reach the generator.
 * This component restates every class the project uses as a plain attribute,
 * which is all the scanner needs. It is never rendered.
 *
 * 486 classes across 16 files.
 */
export function ZeeSafelist() {
  return (
    <>
    <i className="-mt-6 -rotate-6 !pa-8 absolute accent-emerald-500 accent-purple-500 active:scale-95 align-top animate-bounce animate-ping animate-pulse animate-spin" />
    <i className="aspect-video auto-cols-fr backdrop-blur-md backdrop-brightness-125 bg-[rgb(15,118,110)] bg-[rgb(20,184,166)] bg-[rgb(253,242,240)] bg-accent bg-amber-100 bg-amber-500 bg-blue-500 bg-center" />
    <i className="bg-clip-text bg-cover bg-cyan-500 bg-emerald-200 bg-emerald-400 bg-emerald-50 bg-emerald-500 bg-emerald-600 bg-fuchsia-500 bg-fuchsia-600 bg-gradient-to-b bg-gradient-to-bl" />
    <i className="bg-gradient-to-br bg-gradient-to-l bg-gradient-to-r bg-gradient-to-t bg-gradient-to-tl bg-gradient-to-tr bg-green-500 bg-indigo-100 bg-indigo-50 bg-indigo-500 bg-indigo-600 bg-info" />
    <i className="bg-lime-500 bg-lime-600 bg-negative bg-no-repeat bg-orange-500 bg-orange-600 bg-pink-100 bg-pink-500 bg-positive bg-primary bg-purple-100 bg-purple-500" />
    <i className="bg-red-500 bg-red-600 bg-rose-100 bg-rose-400 bg-rose-500 bg-rose-600 bg-secondary bg-sky-500 bg-slate-100 bg-slate-200 bg-slate-300 bg-slate-50" />
    <i className="bg-slate-900 bg-teal-400 bg-teal-500 bg-teal-600 bg-violet-100 bg-violet-500 bg-warning bg-white block blur-sm border border-2" />
    <i className="border-4 border-b border-blue-400 border-collapse border-dashed border-dotted border-emerald-400 border-emerald-500 border-indigo-200 border-indigo-500 border-l border-slate-200" />
    <i className="border-slate-300 border-slate-800 border-t border-teal-500 border-transparent border-violet-400 border-white bottom-2 break-all brightness-150 capitalize caret-pink-500" />
    <i className="col-4 col-8 col-end-4 col-span-2 col-span-full col-start-2 column columns-3 contrast-200 cursor-col-resize cursor-crosshair cursor-grab" />
    <i className="cursor-help cursor-not-allowed cursor-pointer cursor-wait cursor-zoom-in dark:bg-amber-950 dark:bg-black dark:bg-emerald-900 dark:bg-emerald-950 dark:bg-indigo-900 dark:bg-indigo-950 dark:bg-pink-950" />
    <i className="dark:bg-purple-950 dark:bg-rose-950 dark:bg-slate-700 dark:bg-slate-800 dark:bg-slate-900 dark:bg-slate-950 dark:bg-violet-950 dark:border-slate-700 dark:border-slate-800 dark:text-emerald-400 dark:text-indigo-300 dark:text-indigo-400" />
    <i className="dark:text-rose-300 dark:text-slate-200 dark:text-slate-300 dark:text-slate-400 dark:text-slate-500 dark:text-slate-600 dark:text-white disabled:cursor-not-allowed disabled:opacity-50 divide-emerald-300 divide-slate-100 divide-slate-200" />
    <i className="divide-slate-300 divide-x divide-y duration-150 duration-200 duration-300 duration-700 fill-current fill-indigo-500 fill-none first:pt-0 flex" />
    <i className="flex-1 flex-wrap focus-visible:ring-2 focus-visible:ring-violet-500 focus:ring-2 focus:ring-cyan-500 focus:ring-indigo-400 focus:ring-pink-400 font-black font-bold font-light font-medium" />
    <i className="font-mono font-normal font-sans font-semibold font-serif font-thin from-amber-500 from-cyan-400 from-fuchsia-500 from-indigo-500 from-orange-400 from-purple-500" />
    <i className="from-sky-400 from-slate-700 from-yellow-300 fs-2xl fs-4xl fs-base fs-lg fs-sm fs-xs gap-1 gap-10 gap-2" />
    <i className="gap-3 gap-4 gap-5 gap-6 gap-8 gap-x-8 gap-y-2 grayscale grid grid-cols-1 grid-cols-2 grid-cols-3" />
    <i className="grid-cols-4 grid-flow-col grid-rows-2 h-[70px] h-10 h-14 h-16 h-20 h-24 h-28 h-32 h-4" />
    <i className="h-40 h-8 hidden hover:-translate-y-2 hover:bg-emerald-600 hover:bg-indigo-600 hover:bg-indigo-700 hover:bg-slate-100 hover:border-indigo-400 hover:scale-105 hover:scale-110 hover:shadow-2xl" />
    <i className="hover:shadow-lg hover:shadow-xl hover:text-white hue-rotate-90 inline-block inset-4 inset-8 invert italic items-center items-end items-start" />
    <i className="justify-between justify-center last:pb-0 leading-[1.9] leading-loose leading-relaxed leading-snug leading-tight left-2 left-20 left-32 left-6" />
    <i className="lg:border-r lg:col-span-1 lg:col-span-4 lg:grid-cols-4 lg:grid-cols-5 lg:h-screen lg:pa-12 lg:sticky lg:top-0 line-through list-disc list-inside" />
    <i className="lowercase max-w-[42ch] max-w-[62ch] max-w-[68rem] max-w-[70ch] max-w-56 max-w-72 max-w-96 mb-1 mb-12 mb-16 mb-2" />
    <i className="mb-3 mb-4 mb-6 mb-8 md:block md:grid-cols-2 md:grid-cols-4 md:hidden md:pa-10 md:pa-8 min-h-[100vh] min-w-[42rem]" />
    <i className="mix-blend-multiply ml-8 motion-safe:animate-bounce mt-12 mt-16 mt-4 mx-auto no-print odd:bg-slate-50 offset-4 opacity-10 opacity-100" />
    <i className="opacity-25 opacity-50 opacity-70 opacity-75 opacity-80 order-first order-last outline outline-2 outline-blue-500 outline-none outline-offset-2" />
    <i className="overflow-hidden overflow-x-auto overflow-x-hidden overflow-y-auto p-[13px] pa-2 pa-3 pa-4 pa-5 pa-6 pa-8 pb-1" />
    <i className="pb-2 pb-3 pb-8 pe-3 pl-16 placeholder:text-slate-400 pr-4 print:text-black ps-12 pt-2 pt-8 px-10" />
    <i className="px-2 px-3 px-4 px-5 py-1 py-2 py-3 relative resize-y right-2 ring-2 ring-4" />
    <i className="ring-emerald-300 ring-indigo-500 ring-inset ring-offset-2 ring-pink-500 ring-purple-500 rotate-45 rotate-6 rounded rounded-[28px] rounded-2xl rounded-b-2xl" />
    <i className="rounded-full rounded-l-2xl rounded-lg rounded-md rounded-none rounded-r-2xl rounded-sm rounded-t-2xl rounded-xl row row-span-2 saturate-200" />
    <i className="scroll-mt-8 select-all select-none self-end sepia shadow shadow-2xl shadow-inner shadow-lg shadow-md shadow-sm shadow-xl" />
    <i className="shrink-0 skew-x-12 skew-y-6 sm:grid-cols-2 sm:grid-cols-4 snap-center snap-mandatory snap-x space-x-4 space-y-1 space-y-2 space-y-3" />
    <i className="sr-only stroke-2 stroke-current stroke-rose-500 table-auto text-[rgb(231,76,60)] text-body1 text-body2 text-caption text-center text-emerald-600 text-emerald-700" />
    <i className="text-end text-h2 text-h3 text-h4 text-h5 text-indigo-600 text-indigo-700 text-justify text-left text-overline text-right text-rose-700" />
    <i className="text-slate-100 text-slate-400 text-slate-500 text-slate-600 text-slate-700 text-slate-800 text-slate-900 text-subtitle1 text-transparent text-white to-cyan-300 to-cyan-400" />
    <i className="to-indigo-600 to-pink-500 to-purple-600 to-rose-500 to-slate-900 top-2 top-4 tracking-[0.3em] tracking-normal tracking-tight tracking-tighter tracking-wide" />
    <i className="tracking-widest transition transition-colors transition-shadow truncate underline uppercase via-blue-500 via-orange-400 via-purple-500 via-rose-500 w-[220px]" />
    <i className="w-1/2 w-1/3 w-1/4 w-10 w-20 w-24 w-28 w-3/4 w-32 w-4 w-40 w-56" />
    <i className="w-full whitespace-nowrap xl:col-span-5 xl:grid-cols-2 xl:grid-cols-3 xl:grid-cols-6" />
    </>
  );
}
